-- From Lanc // rewrite by Goldfinger and Meradon (originally from TC)
DELETE FROM `script_texts` WHERE entry BETWEEN -1578049 AND -1578000;
INSERT INTO `script_texts` (entry, content_default, content_loc3, content_loc8, sound, type, language, emote, comment) VALUES
-- Drakos the Interrogator
(-1578000,'The prisoners shall not go free. The word of Malygos is law!','Die Gefangenen dürfen nicht entkommen. Malygos Wort ist Gesetz','Узники не вырвутся на волю. Слово Малигоса - закон!',13594,1,0,0,'Drakos Pullaggro'),
(-1578001,'A fitting punishment!','Eine angemessene Strafe!','Заслуженное наказание!',13602,1,0,0,'Drakos kills 1'),
(-1578002,'Sentence: executed!','Urteil: vollstreckt!','Приговор приведен в исполнение!',13603,1,0,0,'Drakos kills 2'),
(-1578003,'Another casualty of war!','Ein Kriegsopfer mehr!','Еще одна жертва войны!',13604,1,0,0,'Drakos kills 3'),
(-1578004,'The war... goes on.','Der Krieg...geht weiter.','Война... продолжается.',13605,1,0,0,'Drakos death'),
(-1578005,'It is too late to run!','Zu spät zum weglaufen!','Поздно убегать!',13598,1,0,0,'Drakos pull 1'),
(-1578006,'Gather \'round!','Sammelt euch!','Станьте в круг!',13599,1,0,0,'Drakos pull 2'),
(-1578007,'None shall escape!','Niemand soll entkommen!','Не кто не уйдет живым!',13600,1,0,0,'Drakos pull 3'),
(-1578008,'I condemn you to death!','Ich verurteile euch zum Tode','Я приговариваю вас к смерти!',13601,1,0,0,'Drakos pull 4'),
(-1578009,'Tremble, worms!','Zittert, Würmer!','Трепещите, черви!',13595,1,0,0,'Drakos stomp 1'),
(-1578010,'I will crush you!','Ich zerschmettere euch!','Я раздавлю вас!',13596,1,0,0,'Drakos stomp 2'),
(-1578011,'Can you fly?','Könnt ihr fliegen?','Вы умеете летать?',13597,1,0,0,'Drakos stomp 3'),
-- Varos
(-1578020,'There will be no mercy!','Erwartet keine Gnade','Пощады не будет!',13649,1,0,0,'Varos aggro'),
(-1578021,'Oculus ours!','Das Oculus ist unser!','Окулус наш!',13654,1,0,0,'Varos kill 2'),
(-1578022,'I warned you!','Ihr wurdet gewarnt','Тебя предупреждали!',13653,1,0,0,'Varos kill 1'),
(-1578023,'They are... too strong! Underestimated their... fortitude.','Sie sind...zu stark! Habe ihre...Kräfte...unterschätzt.','Они... слишком сильны! Я недооценил... их мужество.',13655,1,0,0,'Varos death'),
(-1578024,'Blast them! Destroy them!','Pustet sie weg! Vernichtet sie!','Взорвать их! Изничтожить!',13650,1,0,0,'Varos airstrike 1'),
(-1578025,'Take no prisoners! Attack!','Macht keine Gefangenen! Angriff!','Пленных не брать! В Атаку!',13651,1,0,0,'Varos airstrike 2'),
(-1578026,'Strike now! Obliterate them!','Schlagt zu! Löscht sie aus!','Нанесите удар! Уничтожте их!',13652,1,0,0,'Varos airstrike 3'),
(-1578027,'Intruders, your victory will be short-lived. I am Commander Varos Cloudstrider. My drakes control the skies and protest this conduit. I will see to it personally that the Oculus does not fall into your hands!','Eindringlinge,euer Sieg währt nur kurz. Ich bin der Kommandant Varos Wolkenwanderer. Meine Drachen kontrollieren den Himmel und schützen diese Energiezufuhr. Ich persönlich werde dafür sorgen, dass das Oculus euch nicht in die Hände fällt.','Чужаки, ваш триумф будет не долгим. Я командир Варос Заоблачный странник. Мои драконы обозревают небеса и защищают это место. Я позабочусь, чтобы Окулус не достался вам!',13648,1,0,0,'Varos spawn/ shild break'),
-- Urom
(-1578030,'Poor blind fools!','Arme blinde Narren!','Несчастные слепые глупцы!',13638,1,0,0,'Urom aggro'),
(-1578031,'If only you understood!','Begreift es doch endlich!','Если бы вы только могли понять!',13641,1,0,0,'Urom kill 1'),
(-1578032,'Now do you see? Do you?!','Seht ihr es jetzt? Seht ihr?','Ну что, теперь тебе понятно? Или нет?!',13642,1,0,0,'Urom kill 2'),
(-1578033,'Unfortunate, but necessary.','Tragisch, doch notwendig','Сожелею, это было необходимо.',13643,1,0,0,'Urom kill 3'),
(-1578034,'Everything I\'ve done... has been for Azeroth...','Alles was ich tat...tat ich für Azeroth...','Все что я делал... было во имя Азерота...',13644,1,0,0,'Urom death'),
(-1578035,'A taste... just a small taste... of the Spell-Weaver\'s power!','Ein kleiner...nur ein kleiner Vorgeschmack... der Macht des Zauberwirkers!','Тень... лиш бледная тень... подленного могущества Хранителя магии!',13639,1,0,0,'Urom explosion 1'),
(-1578036,'So much unstable energy... but worth the risk to destroy you!','So viel instabile Energie... doch um euch zu vernichten ist es das Risiko wert!','Много неустойчивой энергии... но чтобы уничтожить вас, я готов рискнуть!',13640,1,0,0,'Urom explosion 2'),
(-1578037,'What do we have here... those would defy the Spell-Weaver? Those without foresight or understanding. How could I make you see? Malygos is saving the world from itself! Bah! You are hardly worth my time!','Was haben wir hier... jene die dem Spruchwirker trotzen? Jene ohne Verstand oder Weitblick? Wie kann ich es euch begreiflich machen? Malygos rettet die Welt vor sich selbst!Pah! Ihr vergeudet meine Zeit!','Так, что у нас тут... ааа вы пришли сразится с Хранителем магии? Это вы то лишенные предвидиния и понимания. Как мне заставить вас прозреть? Малигос спасает мир от самого мира! Эх! На вас жаль тратить время!',13635,1,0,0,'Urom summon 1'),
(-1578038,'Clearly my pets failed. Perhaps another demonstration is in order.','Meine Begleiter haben versagt. Vielleicht ist eine andere Demonstration angebracht.','Моих слуг постигла неудача. Возможно потребуется еще одно предупреждение.',13636,1,0,0,'Urom summon 2'),
(-1578039,'Still you fight. Still you cling to misguided principles. If you survive, you\'ll find me in the center ring.','Ihr kämpft nochimmer. Nochimmer haltet ihr an falschen Prinzipien fest.Wenn ihr überlebt, findet ihr mich im mittleren Ring.','Вы все еще сражаетесь. Все еще цепляетесь за свои ложные убеждения. Если выживите, встретимся в центральном кругу.',13637,1,0,0,'Urom Summon 3'),
-- Eregos
(-1578040,'You brash interlopers are out of your element! I will ground you!','Ihr dreisten Eindringlinge gehört nicht hierher! Ich werde euch ein Ende bereiten!','Нахальные невежды, вы все в небесах летаете! Сейчас я вас заземлю!',13623,1,0,0,'Eregos Aggro'),
(-1578041,'It\'s a long way down...','Es ist ein weiter Weg nach unten...','Как больно падать...',13628,1,0,0,'Eregos kill 1'),
(-1578042,'Back to the earth with you!','Zurück auf den Boden mit Euch!','Вернемся на землю!',13629,1,0,0,'Eregos kill 2'),
(-1578043,'Enjoy the fall!','Geniest den Flug!','Наслаждайся полетом!',13630,1,0,0,'Eregos kill 3'),
(-1578044,'Savor this small victory, foolish little creatures. You and your dragon allies have won this battle. But we will win... the Nexus War.','Feiert ruhig euren kleinen Sieg, einfälltige Geschöpfe.Ihr und eure Drachenverbündeten mögt diesen Kampf gewonnen haben!Doch wir gewinnen... den Nexuskrieg.','Празнуйте свой мелкий триумф, призренные глупцы. Вы и ваши союзники драконы победили в этой битве. Но мы одержим верх в войне... Нексуса.',13631,1,0,0,'Eregos death'),
(-1578045,'We command the arcane! It shall not be used against us.','Wir gebieten über das Arkane! Es wird nicht gegen uns verwendet werden.','Мы повелеваем тайной магией! Она не будет использована против нас.',13626,1,0,0,'Eregos arcan shield'),
(-1578046,'It is trivial to extinguish your fire!','Es ist ein Kinderspiel eure Flammen auszulöschen!','Как легко погасить ваш огонь!',13627,1,0,0,'Eregos fire shield'),
(-1578047,'No magic of nature will help you now!','jetzt hilft euch keine Naturmagie mehr!','Никакая магия природы теперь вас не спасет!',13625,1,0,0,'Eregos natur shield'),
(-1578048,'Such insolence... such arrogance... must be PUNISHED!','Solch Frevel...solch Arroganz...muss bestraft werden!','Какая заносчивость... какая чандливость... вы заслуживаете КАРЫ!',13624,1,0,0,'Eregos frenzy'),
(-1578049,'Simpletons! You cannot comprehend the forces you have set in motion. The ley line conduit will not be disrupted! Your defeat shall be absolute!','Einfallspinsel! Ihr könnte die Kräfte nicht verstehen, die ihr entfesselt habt.Der Leylinienstrom wird nicht unterbrochen! Eure Niederlage wird vernichtend sein!','Простаки! Вам и неведомо какие силы вы привели в действие. Поток энергии не прервется! Вас ждет полный разгром!',13622,1,0,0,'Eregos spawn');
